### ISSUE TITLE
multiple pages not shown in entries table

### ISSUE THREAD

**Issue by cmnstmntmn** [symphonists/pagesfield#16]
if an entry  have multiple pages selected, none of them shows up in entries table.
![screen shot 2014-10-25 at 23 07 25](https://cloud.githubusercontent.com/assets/2312755/4780978/ec6f8900-5c82-11e4-8537-5b8878918cb3.png)

**Comment by designermonkey** [comment]
This is definitely an issue in Symphony 2.5.x

**Comment by nitriques** [comment]
@designermonkey I never works ? I was not even able to reproduce it...

Is it only when the field is the first visible one ?

**Comment by designermonkey** [comment]
Example:

![screen shot 2015-02-02 at 09 49 55](https://cloud.githubusercontent.com/assets/221344/5998599/067d9f1c-aac1-11e4-91b7-f5ab2e920657.png)

**Comment by designermonkey** [comment]
All of those 'None' pages have all pages attached to them.

**Comment by brendo** [comment]
Got this, curious to know if it impacts #21 at all for you @designermonkey? Having trouble reproducing the missing entries!

**Comment by designermonkey** [comment]
Yeah, I just said the same thing to @psychoticmeow, I think it may be related. Will pull this now.
