### ISSUE TITLE
Order by this field broken

### ISSUE THREAD

**Issue by designermonkey** [symphonists/pagesfield#21]
Ordering by this field magically hides entries in the index view.

Without ordering:
![screen shot 2015-02-02 at 09 49 55](https://cloud.githubusercontent.com/assets/221344/5998590/eea7c8e0-aac0-11e4-90d7-2e19225b031a.png)

With ordering:

![screen shot 2015-02-02 at 09 50 06](https://cloud.githubusercontent.com/assets/221344/5998592/f4898aa0-aac0-11e4-852b-d19ba5b6ce26.png)

**Comment by brendo** [comment]
Ah, think I've got this. Seems to lose entries that don't have any value set for the Pages Field

**Comment by designermonkey** [comment]
But then why are they in the list? All entries in our list are attached 
to a page by this field.

Brendan Abbott wrote:

**Comment by brendo** [comment]
Is #16 clouding the picture here?

**Comment by designermonkey** [comment]
Just pulled your update, and this is still an issue :(

**Comment by designermonkey** [comment]
Even changing the order from asc to desc removes entries! This is weird.

**Comment by brendo** [comment]
Very strange, having a bit of a poke around at the moment, hopefully I can turn up something.

**Comment by designermonkey** [comment]
Two of our three removed entries are for the 404 page, one is a new page I added this morning.

**Comment by brendo** [comment]
Check b12f349 out. The joins were incorrect is no value was saved for the pages field.

**Comment by designermonkey** [comment]
Still doing it :(

**Comment by brendo** [comment]
Hmm, well I fixed another related bug then because I had entries missing without that patch!

Are you able to verify if the result is correct from the SQL? I added an `echo $sql` at [this line](https://github.com/symphonycms/symphony-2/blob/master/symphony/lib/toolkit/class.entrymanager.php#L437) and then ran the query in Sequel Pro to verify that the data is actually correct. This will help narrow down if it's the sorting join, or something else that is causing these entries to disappear.

**Comment by designermonkey** [comment]
That definitely pulls all the rows out, yeah, but they don't show in the UI

**Comment by designermonkey** [comment]
Oh, wait, it's limited to 20 rows, when it shouldn't be.

There are 33 rows of data in total, but not that many entries in the table, as some are concatenated togather (when multiple pages are selected).

**Comment by brendo** [comment]
Ah, that might have something to do with it! If there is 33 records, but then a limit is applied to just fetch the first 20 entries, then there is a chance that in those first 20 entries there is the same entry twice (because it's attached to multiple pages)

**Comment by designermonkey** [comment]
Yep, just verified it by looking at the SQL for a normal sort on the first column; 12 rows returned, and any sort that has more than 20 records on the pages field loses entries.

Question is how to fix it for this specific field as the limit is global right?

**Comment by brendo** [comment]
In the `buildSortingSQL` function of Pages Field, can you try adding "GROUP BY `e`.`id` " to the start of the `$sort` variable?

**Comment by designermonkey** [comment]
BOOM!

Problem solved. Can you add that to a commit? I have no repo to use.

**Comment by nitriques** [comment]
AWESOME !!! Thanks guys!
